#-------------------------------
# General Site Settings
title: Gregg Bernstein
logo: # /images/gregg-logo.png # You can add own logo. For example '/images/logo.png'.
description: "The personal site of Gregg Bernstein: researcher & educator, author of Research Practice, and speaker."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gregg.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: greggcorp
  card: summary


#-------------------------------
# Author Settings
author:
  name: Gregg Bernstein
#  bio: I'm a user experience research leader with deep know-how in media and publishing, and I wrote the book <i>Research Practice</i>.
  avatar: '/images/gb_head_home.jpg'

social:
- {icon: "fa-brands fa-linkedin", label: LinkedIn, link: "https://www.linkedin.com/in/greggbernstein"}
- {icon: "fa-brands fa-mastodon", label: Mastodon, link: "https://mastodon.social/@greggcorp"}
- {icon: "fa-solid fa-rss", label: RSS, link: "https://gregg.io/feed.xml"}
# - {icon: "fa-twitter", label: Twitter, link: "https://twitter.com/greggcorp"}

#-------------------------------
# Hero Settings
hero:
  hero__title: Hello! I'm Gregg.
  hero__description: I'm a user experience research leader with deep know-how in media and publishing, and I wrote the book <i>Research Practice</i>. This site is where I work through ideas and share what I've learned. Questions? Get in touch!
  hero__image: '/images/gb_head_home.jpg'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: true # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title: Get updates in your inbox # Add your Title
mailchimp__text: Subscribe to my Research Practicing newsletter to get blog posts (and special announcements) delivered. # Add your description.
# mailchimp__identifier: buttondown.email/api/emails/embed-subscribe/greggcorp # Add your Mailchimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: me@gregg.io # Add your email for contact form
  description: Have a question? Want to book Gregg for your conference, company event, or book club? Please get in touch! # Add a description of your form

# NOTE
# Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
# google-analytics: G-Q1BJREMCX9 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed

future: true